// Precompute the 169x169 preflop all-in equity matrix used by the push/fold
// solver and preflop range math. Each matchup cycles through every
// card-compatible combo pairing so suit interactions are sampled evenly.
//
// Usage: node scripts/build-equity.js [samplesPerMatchup=6000]

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { evaluate } from '../src/engine/evaluator.js';
import { CLASS_COMBOS, NUM_CLASSES } from '../src/engine/ranges.js';
import { makeRng } from '../src/engine/rng.js';

const samples = Number(process.argv[2] || 6000);
const rng = makeRng(20240601);
const used = new Uint8Array(52);
const h1 = new Int8Array(7);
const h2 = new Int8Array(7);

function matchup(a, b) {
  const pairs = [];
  for (const x of CLASS_COMBOS[a]) {
    for (const y of CLASS_COMBOS[b]) {
      if (x[0] !== y[0] && x[0] !== y[1] && x[1] !== y[0] && x[1] !== y[1]) pairs.push([x, y]);
    }
  }
  if (!pairs.length) return null;
  let share = 0;
  for (let i = 0; i < samples; i++) {
    const [x, y] = pairs[i % pairs.length];
    used.fill(0);
    used[x[0]] = used[x[1]] = used[y[0]] = used[y[1]] = 1;
    h1[0] = x[0]; h1[1] = x[1];
    h2[0] = y[0]; h2[1] = y[1];
    for (let k = 2; k < 7; k++) {
      let c;
      do c = (rng() * 52) | 0; while (used[c]);
      used[c] = 1;
      h1[k] = c;
      h2[k] = c;
    }
    const s1 = evaluate(h1);
    const s2 = evaluate(h2);
    share += s1 > s2 ? 1 : s1 === s2 ? 0.5 : 0;
  }
  return share / samples;
}

const t0 = Date.now();
const values = [];
for (let a = 0; a < NUM_CLASSES; a++) {
  for (let b = a; b < NUM_CLASSES; b++) {
    const e = matchup(a, b);
    // AA vs AA style impossible matchups don't exist (pairs always have compatible combos)
    values.push(e === null ? 500 : Math.round(e * 1000));
  }
  if (a % 13 === 12) process.stderr.write(`row ${a + 1}/169 (${((Date.now() - t0) / 1000).toFixed(1)}s)\n`);
}

const out = `// GENERATED by scripts/build-equity.js — do not edit by hand.
// Preflop all-in equity (x1000) of class a vs class b for a <= b, row-major
// upper triangle over the 169 classes (see src/engine/ranges.js for indexing).
// ${samples} samples per matchup, evenly cycled over compatible combo pairs.
export const EQUITY_UPPER = '${values.map((v) => v.toString(36).padStart(2, '0')).join('')}';
`;
const target = join(dirname(fileURLToPath(import.meta.url)), '../src/data/equity169.js');
writeFileSync(target, out);
console.log(`wrote ${values.length} matchups to ${target} in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
