// Headless bot-vs-bot simulation.
//
//   node scripts/simulate.js [hands=600] [scenario=cash] [--calibrate]
//
// Prints each AI profile's measured HUD stats and win rate. With
// --calibrate it writes src/data/profileHud.js, the measured stats the app
// shows on profile cards and uses for "you play like ..." matching.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { Session } from '../src/app/session.js';
import { PROFILES } from '../src/ai/profiles.js';
import { emptyAgg, mergeAgg, deriveStats } from '../src/stats/stats.js';
import { makeRng, shuffle } from './util.js';

const args = process.argv.slice(2);
const calibrate = args.includes('--calibrate');
const nums = args.filter((a) => !a.startsWith('--'));
const targetHands = Number(nums[0] || 600);
const scenario = nums[1] || 'cash';

const rng = makeRng(424242);
const byProfile = new Map();
const t0 = Date.now();
let hands = 0;
let decisions = 0;
const gradeCount = {};

while (hands < targetHands) {
  const lineup = shuffle(PROFILES.map((p) => p.id), rng).slice(0, 8);
  const s = new Session({ scenario, lineup, seed: Math.floor(rng() * 1e9), autoHero: true, heroProfileId: 'gto', continueAfterBust: true });
  let k = 0;
  while (!s.tournament.isOver() && k++ < 150 && hands < targetHands) {
    s.startHand();
    s.runBots();
    s.finishHand();
    hands++;
  }
  for (const d of s.decisions) { gradeCount[d.grade] = (gradeCount[d.grade] || 0) + 1; decisions++; }
  // fold session aggregates into per-profile totals
  s.tournament.seats.forEach((seat, i) => {
    const pid = i === 0 ? 'gto' : s.profiles[i].id;
    const agg = s.sessionAggs.get(seat.name);
    if (!agg) return;
    byProfile.set(pid, mergeAgg(byProfile.get(pid) || emptyAgg(), agg));
  });
  process.stderr.write(`\r${hands}/${targetHands} hands (${((Date.now() - t0) / 1000).toFixed(0)}s)`);
}
process.stderr.write('\n');

const pct = (x) => (x == null ? '  — ' : `${(x * 100).toFixed(0).padStart(3)}%`);
const rows = [];
for (const p of PROFILES) {
  const agg = byProfile.get(p.id);
  if (!agg) continue;
  const d = deriveStats(agg);
  rows.push([p.id, d]);
  console.log(
    `${p.name.padEnd(20)} hands ${String(d.hands).padStart(5)}  VPIP ${pct(d.vpip)} PFR ${pct(d.pfr)} 3B ${pct(d.threeBet)} F3B ${pct(d.foldTo3Bet)} CB ${pct(d.cbet)} FCB ${pct(d.foldToCbet)} AF ${d.af?.toFixed(1).padStart(4)} WTSD ${pct(d.wtsd)} W$SD ${pct(d.wsd)} bb/100 ${d.bb100?.toFixed(1).padStart(6)}`,
  );
}
console.log(`\n${hands} hands, ${((Date.now() - t0) / 1000).toFixed(1)}s. GTO-seat self-grades:`, gradeCount);

if (calibrate) {
  const keep = ['hands', 'vpip', 'pfr', 'threeBet', 'foldTo3Bet', 'steal', 'cbet', 'foldToCbet', 'af', 'wtsd', 'wsd', 'bb100'];
  const data = Object.fromEntries(rows.map(([id, d]) => [id, Object.fromEntries(keep.map((k) => [k, d[k] == null ? null : Math.round(d[k] * 1000) / 1000]))]));
  const out = `// GENERATED by \`node scripts/simulate.js ${targetHands} ${scenario} --calibrate\` — measured HUD stats of each AI
// profile over simulated ${scenario === 'cash' ? '100bb (BB ante)' : scenario} hands. Do not edit by hand.
export const PROFILE_HUD = ${JSON.stringify(data, null, 2)};
`;
  const target = join(dirname(fileURLToPath(import.meta.url)), '../src/data/profileHud.js');
  writeFileSync(target, out);
  console.log(`wrote ${target}`);
}
